In [13]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'a': 
    [np.array([1, 2, 6]), 
     np.array([4, 5, 6, 7]), 
     np.array([7, 8])], 
                   'b': 
    [np.array([1, 2, 3]), 
     np.array([4, 5, 9, 7]), 
     np.array([2, 8])]
})
df

a             b
0     [1, 2, 3]     [1, 2, 3]
1  [4, 5, 6, 7]  [4, 5, 9, 7]
2        [7, 8]        [7, 8]

In [81]:
def get_row_mean(row, col):
    value =  df.loc[row, col].mean()
    return value.astype(float)

def to_array(row, col):
    ar = np.asarray(df.loc[row, col])
    return ar





0       [1, 2, 6]
1    [4, 5, 6, 7]
2          [7, 8]
Name: a, dtype: object

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'a': 
    [np.array([1, 2, 6]), 
     np.array([4, 5, 6, 7]), 
     np.array([7, 8])], 
                   'b': 
    [np.array([1, 2, 3]), 
     np.array([4, 5, 9, 7]), 
     np.array([2, 8])]
})
df

def standardize(col):
    return (df[col] - df[col].map(lambda x: x.mean()))/ df[col].map(lambda x: x.std())

df['a'] = standardize('a')
df['b'] = standardize('b')
df

a  \
0  [-0.9258200997725514, -0.4629100498862757, 1.3...   
1  [-1.3416407864998738, -0.4472135954999579, 0.4...   
2                                        [-1.0, 1.0]   

                                                   b  
0       [-1.224744871391589, 0.0, 1.224744871391589]  
1  [-1.171700198827415, -0.6509445549041194, 1.43...  
2                                        [-1.0, 1.0]

In [2]:
def standardize(col):
    df[col] =  df[col].apply(lambda x: np.array(x))
    return (df[col] - df[col].map(lambda x: x.mean()))/ df[col].map(lambda x: x.std())

df['a'] = standardize('a')
df['b'] = standardize('b')
df

a  \
0  [-0.9258200997725514, -0.4629100498862757, 1.3...   
1  [-1.3416407864998738, -0.4472135954999579, 0.4...   
2                                        [-1.0, 1.0]   

                                                   b  
0     [-1.2247448713915892, 0.0, 1.2247448713915892]  
1  [-1.171700198827415, -0.6509445549041194, 1.43...  
2                                        [-1.0, 1.0]

In [4]:
print(min(df['a'].map(lambda x: x.min())))
df['a']

-1.3416407864998738


0    [-0.9258200997725514, -0.4629100498862757, 1.3...
1    [-1.3416407864998738, -0.4472135954999579, 0.4...
2                                          [-1.0, 1.0]
Name: a, dtype: object

In [94]:
print(df['a'][0])
print(df['a'][1])
print(df['a'][2])

[-0.9258201  -0.46291005  1.38873015]
[-1.34164079 -0.4472136   0.4472136   1.34164079]
[-1.  1.]


In [99]:
print(df['b'][0])
print(df['b'][1])
print(df['b'][2])
min(df['b'].map(lambda x: x.min()))

[-1.22474487  0.          1.22474487]
[-1.1717002  -0.65094455  1.43207802  0.39056673]
[-1.  1.]


-1.224744871391589